# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_v1',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test_v1',
                'lib_path': 'test_v1'},
  'syms': {'test_v1.core': {'test_v1.core.foo': ('core.html#foo', 'test_v1/core.py')}}}
